version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - demo
  sonarqube:
    image: "sonarqube"
    ports:
     - 9000:9000
    networks:
      - demo
  tomcat:
    image: 'tutum/tomcat:6.0'
    ports:
      - 8080:10000
    environment:
      - TOMCAT_PASS=admin
    networks:
      - demo
networks: 
  demo:
  
  
  
